steps:
- task: Kobiton.Kobiton.trigger-automation-test-release-task.Trigger-automation-test@2
  displayName: 'Kobiton Automation Test Executor'
  inputs:
    Kobiton: 'Kobiton API service connection'
    remote-server: 'Kobiton Executor Server service connection'
    gitRepo: 'https://github.com/kobiton/azure-devops.git'
    gitBranch: master
    deviceName: 'Galaxy*'
    devicePlatformVersion: *
    devicePlatformName: Android
    commands: 'mvn test'
    logType: combined
    terminateOnFailedJob: true
